### ISSUE TITLE
in vagrant, installing nodejs through puppet fails

### ISSUE THREAD

**Issue by bewresu** [wesleytodd/YeoPress#100]
I'm trying this out with the ```--advanced``` flag and when provisioning vagrant I can't get past this roadblock:

```
err: /Stage[main]/Nodejs/Exec[clone-node-repo]/returns: change from notrun to 0 failed: Command exceeded timeout at /tmp/vagrant-puppet-1/modules-0/nodejs/manifests/init.pp:12
```
Other times it's this:
```
err: /Stage[main]/Nodejs/Exec[clone-node-repo]/returns: change from notrun to 0 failed: git clone https://github.com/joyent/node.git node-source returned 128 instead of one of [0] at /tmp/vagrant-puppet-1/modules-0/nodejs/manifests/init.pp:12
```

Both cases if I confirm with ```vagrant ssh``` it seems nodejs repo was cloned properly, and I was in fact able to ```sudo make install``` it manually from the cloned source.

After some searching, it seems it's a puppet issue related to this:
https://github.com/alup/puppet-rbenv/issues/14

It must be noted that I installed vagrant-hostsupdater (https://github.com/cogitatio/vagrant-hostsupdater)
and that I also have these modifications in my Vagrantfile, to solve other issues:

```
  # fix stdin: is not a tty (https://github.com/mitchellh/vagrant/issues/1673)
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  # fix warning: Could not retrieve fact fqdn (http://blog.doismellburning.co.uk/2013/01/19/upgrading-puppet-in-vagrant-boxes/)
  config.vm.hostname = "www.myactualsite.domain"

    #vagrant-hostsupdater plugin automatically update /etc/hosts
    config.vm.network :private_network, ip: "192.168.50.4"
    config.hostsupdater.aliases = ["myactualsite.domain"]
    config.hostsupdater.remove_on_suspend = true
```

These are all new to me, but I'm putting this here so others can confirm if it happens to them as well. As for me, as of the moment I'll just move on after installing nodejs manually.

**Comment by wesleytodd** [comment]
So I think we can all agree that Puppet sucks.  There are much better provisioning tools out there now, but I do not have the time to update this project.  If anyone wants to transition it to Ansible that would be awesome, but until then I think we can close out this issue.
