### ISSUE TITLE
Cannot access database

### ISSUE THREAD

**Issue by fmammoli** [wesleytodd/YeoPress#105]
Hi, 
I'm having problems running the generator.
Everything goes fine but, when creating the wp-config.php it outputs the error:

> > Cannot access database
> > Make sure you create the database and update the credentials in the wp-config.php

But i can access the database on CLI using the same user I set on the generator.
Using the generator on verbose did not gave me more information.

Entering http://yeopress.localhost/ gives me a Not Found message.

I'm just starting with wordpress so, sry if its a noob question...
Thx,

**Comment by collapsedwave** [comment]
Getting this same error. Setup is a very standard MAMP configuration, and Yeopress was working as recently as a month ago. I've updated npm, yeoman and the generator in that time, so not sure where the error may have been introduced. Any suggestions?

**Comment by gduprez** [comment]
having the same issue, does anyone figured out this MAMP / Yeopress problem ?

**Comment by wesleytodd** [comment]
You should check your `wp-config.php` and `local-config.php` files.  The local file is one definite difference between yeopress and a raw download.

But really this is just a environment issue, unless you guys can find an error in the way yeopress is generating the configs.  But I am pretty sure it is fine in most cases.  Maybe you all are hitting edge cases, but unless you can figure it out on your systems I am not much help.

**Comment by gduprez** [comment]
Hi Welsey, thanks for the answer, i'll try to have a look on it later, 
keep you in touch.
