### ISSUE TITLE
fatal: CRLF would be replaced by LF in SVG file

### ISSUE THREAD

**Issue by lemattma** [wesleytodd/YeoPress#106]
Hello, I'm getting this error when trying to run `yo wordpress --advanced`

![screen shot 2014-06-07 at 12 56 51 pm](https://cloud.githubusercontent.com/assets/385858/3209284/7aaefd2c-ee65-11e3-95dc-48d7a5da6342.png)

My config is this:

![screen shot 2014-06-07 at 12 58 42 pm](https://cloud.githubusercontent.com/assets/385858/3209286/86a778fc-ee65-11e3-9566-75cc9cb3325b.png)

```bash
node -v
v0.10.28

yo -v
1.1.2

npm -v
1.4.14
```

Any idea of why is this happening?

Thank you!

**Comment by wesleytodd** [comment]
My only guess is that the file has windows style line endings, but the generator is being run on something other than that, like osx or *nix.

If you are still having this issue, or if you have a solution feel free to re-open this.
