### ISSUE TITLE
Scaffolding plugin from github

### ISSUE THREAD

**Issue by lucifer13** [wesleytodd/YeoPress#118]
Hi and thanks so much for your work! all contributors!
I just discovered YeoPress, and it improved so much my WP workflow!

I like the possibility to scaffold also plugin and would love if it was possible:
- to choose the destination' folder
- to install plugin based on Github url or user/repo/branch (like for the theme).

I'm most of the time installing the same plugins at the beginning of new projects; basically helper class plugin that I install in the mu-plugin folder.

Any plan for such development?

Thanks in advance,

olivier

**Comment by wesleytodd** [comment]
Going to close this, but if you want to actually build out this feature then I would happily accept a pull request.
