### ISSUE TITLE
Github repo caching?

### ISSUE THREAD

**Issue by thesublimeobject** [wesleytodd/YeoPress#121]
For some reason, when I build out a new project yeopress continues to pull from older versions of my github theme repo. This has happened continuously for quite awhile through several updates and I can't figure out why. Does yeopress/yeoman cache these files?

**Comment by benjaminallison** [comment]
Just had this happen to me. Developing a theme, and keep pulling it into new sites using Yeopress, and I'm getting a version that was several commits ago. Seems like this is a Yeoman issue but was possibly resolved:

https://github.com/yeoman/generator/pull/247
