### ISSUE TITLE
Sourcemaps not working with YeoPress

### ISSUE THREAD

**Issue by patrickbjohnson** [wesleytodd/YeoPress#126]
Running into weird issues where sourcemaps are enabled by default with Sass/Grunt but I can't figure out how to resolve the error. [Based on this thread from grunt-contrib-sass](https://github.com/gruntjs/grunt-contrib-sass/issues/25) it looks as though adding `sourcemap: true` should resolve the issue but I continue to get this error: 

`Warning: DEPRECATION WARNING: Passing --sourcemap without a value is deprecated.
Sourcemaps are now generated by default, so this flag has no effect.
Error: Error generating source map: couldn't determine public URL for the source stylesheet.
         No filename is available so there's nothing for the source map to link to.
        on line  of standard input
  Use --trace for backtrace. Use --force to continue.`

Not sure how to move forward. I love this yeoman generator but may have to forego if I cannot resolve this issue.

**Comment by wesleytodd** [comment]
Sounds like updating sass is the answer according to that issue.  I had a similar issue at work with some coworkers that were running old versions of sass with the gulp sass task.  I believe that updating to sass fixed it for them.

Either way, not an issue with yeopress.  Sorry I cannot help you :(
