### ISSUE TITLE
Generator doesn't terminate

### ISSUE THREAD

**Issue by gaswirth** [wesleytodd/YeoPress#127]
Hi there,

When I run YeoPress, everything goes swimmingly until I get to the very end, where I'm presented with the "check your `wp-config.php`...." message, at which point I have to manually abort the process with Ctrl+C to get back to a prompt. I'm trying to run YeoPress from a simple shell script that performs other tasks (to be clear, this happens when I run a simple "yo wordpress" or when it runs from the script), but since the generator never terminates, my script can't continue.

Apologies if this is a dumb issue/question, but I wasn't able to find anything related, and this is all quite new to me!

**Comment by gaswirth** [comment]
I seem to have narrowed this down to selecting "a" when told that WordPress is already installed, as opposed to "Y" (or simply hitting 'enter')!

Thank you!

**Comment by wesleytodd** [comment]
Glad I could help ;)

**Comment by gaswirth** [comment]
Whelllp......I'm a superjerk. I was totally wrong about the prompt being the culprit. Turns out, when I supply database login credentials that don't work, the script finishes fine--if I give the script real, working login values, the script hangs/freezes/has a beer at the final "only human" message.

**Comment by wesleytodd** [comment]
Possibly this: https://github.com/wesleytodd/wp-util/pull/3

**Comment by wesleytodd** [comment]
Let me know if the newest version of the generator works, it has that fix in it.

**Comment by gaswirth** [comment]
Yep! That did it! You rock!

Nick Gaswirth
-----
*Roundhouse Designs*
roundhouse-designs.com

**Comment by wesleytodd** [comment]
Thank @Toddses, he's the one that rocks.

**Comment by Toddses** [comment]
pew pew!

going to go ahead and close this one.
