### ISSUE TITLE
Adding "theme name" tags to template?

### ISSUE THREAD

**Issue by benjaminallison** [wesleytodd/YeoPress#128]
So when scaffolding with a theme, YeoPress, asks me what the theme directory should be. It would be really neat YeoPress could also populate specified tags within my theme.

Example, say my theme name is `mysite`. In my `functions.php` file, I have the following function:

```php
<%themeName%>_init function() {
// code
}
```

Well, when YeoPress does it's thang, it could look for that tag <%themeName%>, turning that function into:

```php
mysite_init function() {
// code
}
```

One great application is in the `wp_register_script` declaration for livereload:

``` php
wp_register_script('livereload', 'http://localhost/<%themeName%>:35729/livereload.js?snipver=1', null, false, true);
```

becomes

``` php
wp_register_script('livereload', 'http://localhost/mysite:35729/livereload.js?snipver=1', null, false, true);
```

Just an idea!

**Comment by wesleytodd** [comment]
I think there is the possibility that it might just work that way.  I cannot find in the yeoman docs which methods get parsed for templates on a remote call, but it uses the normal built-in copy methods (`directory` and `tarball`), which I think process templates.  Did you try it and it didn't work?

**Comment by benjaminallison** [comment]
Huh. I'm new to Yeoman and didn't even know anything like that was possible! Cool.

The idea was that a value I entered into YeoPress would be used to fill the template tag (say, when I'm asked what the theme directory is called). Is that value exposed in some way that a template tag could work with?

**Comment by wesleytodd** [comment]
I think that by default it will use the input which is attached to the generator instance.  Take a look at the templates in [app/tempaltes](https://github.com/wesleytodd/YeoPress/blob/master/app/templates/) for examples.  The values in the prompts are in the prompts.js file.

Let me know what you find.

**Comment by benjaminallison** [comment]
Awesome! Wherever I throw `<%= conf.get('themeDir') %>` in my Wordpress theme files, it's replaced with the value I entered for the custom theme directory name. So great!

**Comment by wesleytodd** [comment]
Great!  So can we close this?

**Comment by benjaminallison** [comment]
Close it up!

Even though it's a Yeoman thang, might be worth adding a sentence or two to the docs...

--
Benjamin Allison
Designer
