### ISSUE TITLE
Don't work for me

### ISSUE THREAD

**Issue by imacnu** [wesleytodd/YeoPress#130]
Is necessary MAMP or similar?

1. Create a DB localhost:8888/phpMyAdmin (ex: database)
2. On terminal go to folder of MAMP server (ex documents/apache/worpressYeoman)
3. yo wordpress (error access database (parameters are correct))
4. URL ?? which?? try with many but don't work
5. localhost / database / root / root
6. Use git default and directory yeopress
7. Go to URL ( don't work)
8. Go to localhost:8888/wordpressYeoman (ok, install wordpress)
9. Go to documents/apache/worpressYeoman and run grunt
10. Select Theme (don't work styles, live reload, ...)

When i try change a global.scss i recive error "Sass::SyntaxError: Error generating source map: couldn't determine public URL for the source stylesheet.\A   No filename is available so there's nothing for the source map to link to.\A ";

Whats happend?? Thanks

**Comment by wesleytodd** [comment]
Sorry, but I am not sure what your problems are.  You do need a web server setup with MySQL.  For the sass thing, I had this issue on another project and updating sass fixed it for me.

**Comment by imacnu** [comment]
I have installed MAMP with Mysql, accesible in localhost:888/yeopress installation but always print error "database is not accesible" or similar, but its not true.

I tried with virtual host (MAMP PRO) but don't work ...

**Comment by wesleytodd** [comment]
The generator will throw that error if it cannot find your mysql instance.  But if the site works than you should just ignore it.  It is just a warning anyway.

Really this is about your configuration, not the generator.  Sorry I cannot be of more help.

**Comment by fseminario** [comment]
@wesleytodd First off, great job with this generator! Thanks for all the time spent creating it. 

I am running into a similar problem. I'm able to install WP with MAMP fine, without the generator, using the same db connection info.

My warning is "cannot access database", which is not a big deal because I can configure the wp-config.php but I checked the code and they are almost the same with the except of the if statements

Top is yo-wordpress and bottom is wp/mamp

![screen shot 2015-04-24 at 2 49 01 pm](https://cloud.githubusercontent.com/assets/4037582/7329146/265cdca2-ea91-11e4-8b32-02b1b65d5b71.png)

**Comment by wesleytodd** [comment]
@fseminario You could try printing out the values for those if not defined calls.  Maybe one of those variables is defined for some reason.  Is it possible you have the local config file and are setting them there as well?

**Comment by fseminario** [comment]
Before that I just decided to try something else.

I was able to do an simple install, still not being able to connect to the db, but started encountering a bunch of missing .php files. 

![screen shot 2015-04-24 at 3 29 17 pm](https://cloud.githubusercontent.com/assets/4037582/7329675/b7027172-ea96-11e4-8d31-f97bc9e4a236.png)

I went ahead and copied over the missing .php from an original WP setup folder and it worked. I was going to generate a list but it was so many that I figure I just send a screenshot. 

Left: Original WP
Right: yo wordpress

![screen shot 2015-04-24 at 3 24 46 pm](https://cloud.githubusercontent.com/assets/4037582/7329627/2ce996aa-ea96-11e4-939c-714ba4b969b7.png)

I also configured the wp-config.php with the same exact db info and it works after that.

![screen shot 2015-04-24 at 3 28 45 pm](https://cloud.githubusercontent.com/assets/4037582/7329670/9e7d0e96-ea96-11e4-88ad-694be019cc30.png)

**Comment by wesleytodd** [comment]
That is #147 #149 #150 and the one where we solved the issue #148.  It hasn't been released yet because we found another issue with the files being copied over.  If you feel like fixing #153 we can release and it should solve most of these problems.
