### ISSUE TITLE
Error generating source map: 

### ISSUE THREAD

**Issue by ehijzen** [wesleytodd/YeoPress#140]
in a clean first install, 'grunt' and 'grunt setup' gave me the following error:

Warning: Error: Error generating source map: couldn't determine public URL for the source stylesheet.
         No filename is available so there's nothing for the source map to link to.
        on line  of standard input
  Use --trace for backtrace. Use --force to continue.

Aborted due to warnings.

this is how I solved it

    npm install npm-check-updates 

And then run the following

    npm-check-updates will tell you which packages are outdated
    npm-check-updates -u will update those packages in your package.json
    npm update to update all your outdated packages.

**Comment by Toddses** [comment]
I'm assuming this was with installing the theme template?

**Comment by ehijzen** [comment]
Yes with the theme template.
After this small fix it worked perfectly.

**Comment by ospaarmann** [comment]
I had the same issue. The problem for me was, that newer versions of the SASS gem didn't play along with the old version of grunt-contrib-sass configured in package.json. I had to update the version to 0.9.2 and run npm install after that to fix the issue.

**Comment by wesleytodd** [comment]
If you want to put together a small PR to bump that version it would be awesome!!  You can find the template branch here: https://github.com/wesleytodd/YeoPress/tree/template-develop

Once you make the update and we test it we can merge that branch to master for everyone to use.

**Comment by ospaarmann** [comment]
Done.

**Comment by wesleytodd** [comment]
Closing!  Thanks for the good work!
