### ISSUE TITLE
http://localhost/cms/wp-admin/install.php - This webpage is not available

### ISSUE THREAD

**Issue by lukephills** [wesleytodd/YeoPress#142]
Hi there,

I set the URL to http://localhost:8888/FEMUR and everything set up fine using your custom theme but when I go to the URL it changes to this: http://localhost/cms/wp-admin/install.php and the page cannot be found.

If I change the link to http://localhost:8888/FEMUR/cms/wp-admin/install.php the page loads but all it's dependencies can not be found because they are using the localhost/cms directory that doesn't exist. Any ideas what I've filled out incorrectly? 

Here are my settings:
? WordPress URL: http://localhost:8888/FEMUR
? Table prefix: wp_
? Database host: localhost
? Database name: femur
? Database user: root
? Database password: root
? Use Git? Yes
? Would you like to install WordPress as a submodule? Yes
? WordPress install directory: cms
? WordPress content directory: content
? Install a custom theme? Yes
? Destination directory: yeopress
? Theme source type (git/tar) git
? Task runner (grunt/gulp) grunt
? GitHub username: wesleytodd
? GitHub repository name: YeoPress
? Repository branch: template
? Does this all look correct? Yes

**Comment by wesleytodd** [comment]
Installing to a subdirectory is apparently not working.  Someone submitted a PR for this the other day (#137) but it was not fully correct either.  If you want to fix that PR then we would happily merge it.  Currently the only way is to manually setup the proper wp-config values that work with your setup.

Closing a duplicate.
