### ISSUE TITLE
vinyl-fs error

### ISSUE THREAD

**Issue by aadesh** [wesleytodd/YeoPress#145]
I keep getting this error every time I try to install this generator. Can anybody help find out whats going wrong?

Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory

Everything looks all right!
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/Users/Aadesh/.npm-packages/bin/npm" "install" "-g" "yo" "generator-wordpress"
npm ERR! node v0.13.0-pre
npm ERR! npm  v2.7.1
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: vinyl-fs@'>=0.3.7 <0.4.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.1","0.0.2","0.1.0","1.0.0"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'download'
npm ERR! notarget 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Aadesh/test/wordpress/npm-debug.log

**Comment by wesleytodd** [comment]
Try running `npm cache clean` and making sure the location it tried to install it to is removed, `/usr/local/node_modules/generator-wordpress` on *nix.  Then try again.  If you still have the problem them post back.

**Comment by wesleytodd** [comment]
Feel free to re-open if you want to pick this back up
