### ISSUE TITLE
Got directory of undefined type error when project name contains underscore

### ISSUE THREAD

**Issue by theoptips** [wesleytodd/YeoPress#157]
Got this error and try to yeopress into a project/app directory who name contains underscores
example: test_wordpress

            remote.directory('.', this.conf.get('wpDir'));
                  ^
TypeError: Cannot read property 'directory' of undefined

**Comment by Toddses** [comment]
Just for reference, can you check your yeopress version?

Sounds a lot like #147 #149 #150, though this would be the first time with the underscore thing.

**Comment by alextegelid** [comment]
I'm seeing the same error, however my directory contains only lowercase letters (using the directory name _wordpress_ for debug purposes). I've made multiple tries, cleaning the `~/.cache/yeoman` before each try.

**Comment by Toddses** [comment]
Pop open YeoPress's package.json, and change the version of yeoman-generator to 0.19.2, and reinstall yeoman-generator. Let us know if that does the trick @alextegelid @theoptips

**Comment by wesleytodd** [comment]
@Toddses Maybe i should release that version despite the other problems?  I haven't had time to deal with them.  What do you think?

**Comment by Toddses** [comment]
@wesleytodd Yeah I think so, too. It would probably be better to have a working version out there, even with a deprecation warning, than a non-working version.

**Comment by wesleytodd** [comment]
Ok, published.

**Comment by alextegelid** [comment]
@wesleytodd This update works fine on my machine. Thanks!

**Comment by wesleytodd** [comment]
@alextegelid Awesome!!  Sorry for the issues, wordpress's repo had some weird conflict with the unzip library that Yeoman used.  And then we had some other weird issue with template strings inside some wordpress core files.  Anyway, it was a pain of a release and so was sitting there for a bit :(

**Comment by wesleytodd** [comment]
@theoptips Re-open this if it did not fix the issue for you.  Thanks!!
