### ISSUE TITLE
Unable to use Gulp task runner as a default

### ISSUE THREAD

**Issue by keeprock** [wesleytodd/YeoPress#161]
When installing Yeopress, I chose Gulp as my Task Runner. But in the end of installation I see "gulpfile.js missing!" and Grunt appears in theme folder with no signs of Gulp at all. Even in package.json

I use the latest version of YeoPress, Yeoman and Gulp/Grunt.

Does this a normal scenario and we should put our own gulpfile.js to build a processes we need or am I miss something?

Thanks in advance.

**Comment by Toddses** [comment]
Are you using the YeoPress theme?

**Comment by keeprock** [comment]
Yeah

**Comment by Toddses** [comment]
That theme currently only supports Grunt. If you pull in your own theme, you can use gulp and include a gulpfile in there. Sorry for the confusion there. We should def make it more clear in a future release.

**Comment by keeprock** [comment]
@Toddses thanks for quick reply. Is it planned in future releases or its a good idea to fork it and make it my own?

**Comment by Toddses** [comment]
Dude if you fork it and make a version of the theme that uses gulp, I am @wesleytodd agree with me and we'd pull it into the project.

**Comment by keeprock** [comment]
@Toddses I got it :)

**Comment by wesleytodd** [comment]
For sure!!!!
