### ISSUE TITLE
Not pulling down all files

### ISSUE THREAD

**Issue by nathanaelphilip** [wesleytodd/YeoPress#166]
Is anyone else having trouble with yo not installing all of the wordpress files?

**Comment by Toddses** [comment]
Sounds like you might be running an older version of YeoPress. Try to update and let us know if that took care of it.

**Comment by escobar022** [comment]
don't forget to clearing the cache for npm! ( rm -rf ~/.cache/* on Mac )

**Comment by Toddses** [comment]
i always forget about that part :) thanks.

**Comment by nathanaelphilip** [comment]
I think clearing the cache worked. Thanks @escobar022 & @Toddses .
