### ISSUE TITLE
Gruntfile and package.json are not generating automatically

### ISSUE THREAD

**Issue by ui-aliraza** [wesleytodd/YeoPress#174]
I was expecting a couple of grunt tasks and package.json automatically created on the root of my project folder - which did not happen. Can you please explain what needs to be done in order to run grunt.

Attaching screenshot below for you to identify any potential issue caused during setup.

![screen shot 2015-09-29 at 8 11 58 pm](https://cloud.githubusercontent.com/assets/5379707/10168501/87c225de-66e6-11e5-827c-f8f931c91cc9.png)

**Comment by Toddses** [comment]
Well the theme you are pulling in (ui-aliraza/pubweb-local) looks to be empty. When you're pulling in a custom theme, YeoPress automatically runs `npm install` in the theme directory. Since there's no package manifest, and in fact no files, `npm install` does nothing.
