### ISSUE TITLE
LiveReload and Local Server like MAMP.

### ISSUE THREAD

**Issue by jhauraw** [wesleytodd/YeoPress#4]
Hi Wesley,

Great work on the YeoPress! Thank you very much for putting it together.

Not really an issue, but I wanted to put it down for others in case they are confused like I was.

After getting the generator all setup and if using the YeoPress theme, it took me a while to figure out how you were getting LiveReload working with Yeoman and PHP, since the grunt server doesn't parse it in Yo.

Then I realized you must be using a local server like MAMP/WAMP. Once I set up a virtual host for my root directory where YeoPress was installed, I had it all working.

So some instruction could be added like:
### After Install Completes
1. Setup a local vhost in MAMP (or whatever local dev server) for the YeoPress WP root directory, if not already.
2. Edit `hosts` file with new vhost ServerName, if not already.
3. Go back to Terminal and run `$ grunt`
   (`$ grunt server` won't work, not defined, wouldn't work anyway because of PHP)
4. Jump to the browser and enter your localhost URL, i.e. `http://yeopress.local`
5. If Wordpress appears, all good.
6. Edit JS, SaSS and PHP and watch LiveReload magic in the browser.

Hope that helps,

~J

**Comment by v3nt** [comment]
does anyone have their grunt file to share ? I can't get this to work at all...

**Comment by wesleytodd** [comment]
To be absolutely honest, I haven't installed the theme in a long time.  It could probably use some TLC if anyone wants to take a look.  It could probably be converted to gulp or webpack seeing as grunt is basically dead :)

**Comment by v3nt** [comment]
yeh its on an old setup with grunt i need it for...
